# Generated by Django 4.1.1 on 2022-10-18 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(default=None, max_length=200)),
                ("program", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
                ("total_credit", models.IntegerField()),
                ("description", models.TextField(default=None, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
