# Generated by Django 4.1.1 on 2022-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coordinator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="c_code",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_credit",
            field=models.IntegerField(default=0),
        ),
    ]
