# Generated by Django 4.1.1 on 2022-10-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coordinator", "0002_course_c_code_alter_course_total_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="total_credit",
            field=models.FloatField(default=0),
        ),
    ]
