# Generated by Django 4.1.1 on 2022-10-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Coordinator", "0003_alter_course_total_credit"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="department",),
        migrations.RemoveField(model_name="course", name="program",),
    ]
