# Generated by Django 4.1.1 on 2022-10-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coordinator", "0004_remove_course_department_remove_course_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_outline",
            field=models.FileField(
                blank=True, null=True, upload_to="static/courseOutline"
            ),
        ),
    ]
