# Generated by Django 4.1.1 on 2022-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0007_assignedcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
