# Generated by Django 4.1.1 on 2022-11-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionAdmin', '0012_alter_assign_program_coordinator'),
        ('Coordinator', '0008_course_is_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=300)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstitutionAdmin.program')),
            ],
        ),
    ]
