# Generated by Django 4.1.1 on 2022-12-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0010_alter_program_outcome_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
    ]
