# Generated by Django 4.1.1 on 2022-10-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_is_instit_alter_user_is_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_instit',
            new_name='is_admin',
        ),
    ]
