# Generated by Django 4.1.1 on 2022-10-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_user_is_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(default="", max_length=200),
        ),
    ]
