# Generated by Django 4.1.1 on 2022-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('insititution', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Coordinator',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('insititution', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Instructor',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('insititution', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
    ]
