# Generated by Django 4.1.1 on 2022-09-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('established_on', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=200)),
                ('semester_length', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Outcome',
            fields=[
                ('p_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Session',
            fields=[
                ('csid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=20)),
                ('total_CO_marks', models.BigIntegerField()),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.course_coordinator')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.course_instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.department'),
        ),
    ]
