# Generated by Django 4.1.1 on 2022-10-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_course_department_semester_program_outcome_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Admin", new_name="institutionAdmin",),
    ]
