# Generated by Django 4.1.1 on 2022-10-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_admin_institutionadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_coordinator',
            name='number',
        ),
        migrations.RemoveField(
            model_name='course_instructor',
            name='number',
        ),
        migrations.RemoveField(
            model_name='institutionadmin',
            name='number',
        ),
        migrations.AlterField(
            model_name='course_coordinator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course_instructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institutionadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
