# Generated by Django 4.1.1 on 2022-11-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Coordinator", "0009_program_outcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assigned_CO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_assigned", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PdfFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=500)),
                (
                    "filepath",
                    models.FileField(null=True, upload_to="files/", verbose_name=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "course_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.assignedcourses",
                    ),
                ),
                (
                    "course_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Instructor.assigned_co",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.program_outcome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course_Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_code", models.CharField(default=None, max_length=200)),
                ("description", models.TextField(default=None, max_length=300)),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "course_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.assignedcourses",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assigned_co",
            name="co",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Instructor.course_outcome",
            ),
        ),
    ]
