# Generated by Django 4.1.1 on 2022-11-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coordinator', '0009_program_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=300)),
                ('course_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('course_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.program_outcome')),
            ],
        ),
    ]
