<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-11-15 16:38
=======
# Generated by Django 4.1.1 on 2022-11-15 15:07
>>>>>>> 3276dc26ec473bff520cb0dee698b6f3fd07dab1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("Coordinator", "0009_program_outcome"),
=======
        ('Coordinator', '0009_program_outcome'),
>>>>>>> 3276dc26ec473bff520cb0dee698b6f3fd07dab1
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Course_Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_code", models.CharField(default=None, max_length=200)),
                ("description", models.TextField(default=None, max_length=300)),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "course_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.assignedcourses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PdfFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=500)),
                (
                    "filepath",
                    models.FileField(null=True, upload_to="files/", verbose_name=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "course_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.assignedcourses",
                    ),
                ),
                (
                    "course_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Instructor.course_outcome",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coordinator.program_outcome",
                    ),
                ),
=======
            name='Course_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=300)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('course_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses')),
            ],
        ),
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('course_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.program_outcome')),
>>>>>>> 3276dc26ec473bff520cb0dee698b6f3fd07dab1
            ],
        ),
    ]
