# Generated by Django 4.1.1 on 2022-11-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assigned', models.BooleanField(default=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome')),
            ],
        ),
        migrations.AlterField(
            model_name='mapping',
            name='course_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.assigned_co'),
        ),
    ]
