# Generated by Django 4.1.1 on 2022-11-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0009_program_outcome'),
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='program',
        ),
        migrations.RemoveField(
            model_name='students',
            name='semester',
        ),
        migrations.AlterField(
            model_name='students',
            name='c_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.students')),
            ],
        ),
    ]
