# Generated by Django 4.1.1 on 2022-12-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='weight',
        ),
        migrations.AddField(
            model_name='course_outcome',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapping',
            name='course_outcome',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome'),
            preserve_default=False,
        ),
    ]
