# Generated by Django 4.1.1 on 2022-11-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_outcome',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
