# Generated by Django 4.1.1 on 2022-11-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Instructor", "0003_pdffiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdffiles",
            name="name",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=300)),
                ("student_id", models.CharField(default=None, max_length=20)),
                ("program", models.CharField(default=None, max_length=100)),
                ("semester", models.IntegerField(default=0)),
                (
                    "c_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Instructor.course_outcome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("exam_type", models.CharField(default=None, max_length=100)),
                (
                    "c_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Instructor.course_outcome",
                    ),
                ),
            ],
        ),
    ]
