# Generated by Django 4.1.1 on 2022-12-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('totalmarks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField(default=None, max_length=3000)),
                ('type', models.CharField(default=None, max_length=20)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome')),
            ],
        ),
    ]
