# Generated by Django 4.1.1 on 2022-12-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0011_assignedcourses_is_mapped'),
        ('Instructor', '0004_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='course_assigned',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses'),
        ),
    ]
