# Generated by Django 4.1.1 on 2022-12-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0011_assignedcourses_is_mapped'),
        ('Instructor', '0009_alter_result_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('overall', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('program', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('course_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.assignedcourses')),
            ],
        ),
    ]
