# Generated by Django 4.1.1 on 2022-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0010_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subsection',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
