# Generated by Django 4.1.1 on 2022-12-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0011_questions_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='course_outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome'),
        ),
        migrations.AlterField(
            model_name='result',
            name='course_outcome',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Instructor.course_outcome'),
        ),
    ]
