# Generated by Django 4.1.1 on 2022-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
