# Generated by Django 4.1.1 on 2022-10-18 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("InstitutionAdmin", "0004_alter_program_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="All_Coordinators",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("p_name", models.CharField(default=None, max_length=200)),
                ("isAssigned", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="program",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
