# Generated by Django 4.1.1 on 2022-10-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("InstitutionAdmin", "0005_all_coordinators_alter_program_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="all_coordinators", name="p_name",),
        migrations.AddField(
            model_name="all_coordinators",
            name="coordinator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="p_name",
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="Assign_Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InstitutionAdmin.all_coordinators",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InstitutionAdmin.program",
                    ),
                ),
            ],
        ),
    ]
