# Generated by Django 4.1.1 on 2022-10-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InstitutionAdmin", "0007_alter_program_p_name"),
    ]

    operations = [
        migrations.DeleteModel(name="Assign_Program",),
    ]
