# Generated by Django 4.1.1 on 2022-10-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InstitutionAdmin", "0008_delete_assign_program"),
    ]

    operations = [
        migrations.DeleteModel(name="All_Coordinators",),
    ]
