# Generated by Django 4.1.1 on 2022-10-18 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InstitutionAdmin', '0009_delete_all_coordinators'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Coordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAssigned', models.BooleanField(default=False)),
                ('coordinator', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
