# Generated by Django 4.1.1 on 2022-10-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionAdmin', '0010_all_coordinators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstitutionAdmin.all_coordinators')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InstitutionAdmin.program')),
            ],
        ),
    ]
